const products = [
    {
        id: 0,
        name: "Jabłko",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "ziarnkowe",
        price: 2,
        image: "./fruits-img/apple/jpg",
        // sale: true,
        // saleAmount: 200,
    },
    {
        id: 1,
        name: "Gruszka",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "ziarnkowe",
        price: 4,
        image: "./fruits-img/pear-1280.jpg",
        smallImage: "./fruits-img/pear-640.jpg",
        // sale: true,
        // saleAmount: 200,
    },
    {
        id: 2,
        name: "Truskawka",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "jagodowe",
        price: 10,
        image: "./fruits-img/strawberry-1280.jpg",
        smallImage: "./fruits-img/strawberry-640.jpg",
        // sale: true,
        // saleAmount: 200,
    },
    {
        id: 3,
        name: "Mandarynka",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "cytrusy",
        price: 4.58,
        image: "./fruits-img/apple/jpg",
        // sale: true,
        // saleAmount: 200,
    },
    {
        id: 4,
        name: "Banan",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "egzotyczne",
        price: 6.99,
        image: "./fruits-img/banana-1280.jpg",
        smallImageimage: "./fruits-img/banana-640.jpg",
        // sale: true,
        // saleAmount: 200,
    },
    {
        id: 4,
        name: "Śliwka",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "pestkowe",
        price: 10,
        image: "./fruits-img/apple/jpg",
        // sale: true,
        // saleAmount: 200,
    },
    {
        id: 6,
        name: "Cytryna",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "cytrusy",
        price: 6.50,
        image: "./fruits-img/apple/jpg",
        // sale: true,
        // saleAmount: 200,
    }
];

// pestkowe, ziarnkowe, jagodowe, cytrusy, egzotyczne